/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentDatabaseSystem;

import static StudentDatabaseSystem.StudentDetails.stuID;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rashm
 */
public class StudentResults extends javax.swing.JFrame {

    static String stuID = "0";
    /**
     * Creates new form StudentResults
     */
    public StudentResults() {
        initComponents();
        
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        
        this.setExtendedState(StudentResults.MAXIMIZED_BOTH);
    }
    public void clearAll(){
        jTextField1.setText("");
        jTextField2.setText("");
        
        jComboBox1.setSelectedItem("-");
        jComboBox2.setSelectedItem("-");
        jComboBox3.setSelectedItem("-");
        jComboBox4.setSelectedItem("-");
        jComboBox5.setSelectedItem("-");
        jComboBox6.setSelectedItem("-");
        jComboBox7.setSelectedItem("-");
        jComboBox8.setSelectedItem("-");
        
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Results");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Student Results");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 169, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Index Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Student Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Excel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 40, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Word");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 40, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Power Point");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 40, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Access");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 40, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField1MouseMoved(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField1MouseReleased(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 278;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 67, 0, 0);
        getContentPane().add(jTextField1, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 278;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 67, 0, 0);
        getContentPane().add(jTextField2, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox1MouseMoved(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox1MouseExited(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 67, 0, 0);
        getContentPane().add(jComboBox1, gridBagConstraints);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 67, 52, 0);
        getContentPane().add(jComboBox2, gridBagConstraints);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 67, 0, 0);
        getContentPane().add(jComboBox3, gridBagConstraints);

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 67, 0, 0);
        getContentPane().add(jComboBox4, gridBagConstraints);

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Pass", "Repeat" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 37, 0, 0);
        getContentPane().add(jComboBox5, gridBagConstraints);

        jComboBox6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Pass", "Repeat" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 37, 0, 0);
        getContentPane().add(jComboBox6, gridBagConstraints);

        jComboBox7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Pass", "Repeat" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 37, 0, 0);
        getContentPane().add(jComboBox7, gridBagConstraints);

        jComboBox8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Pass", "Repeat" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 37, 52, 0);
        getContentPane().add(jComboBox8, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 70, 0, 36);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 70, 0, 36);
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setText("ClearAll");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 70, 0, 36);
        getContentPane().add(jButton3, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 70, 0, 36);
        getContentPane().add(jButton4, gridBagConstraints);

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 70, 0, 36);
        getContentPane().add(jButton5, gridBagConstraints);

        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 70, 52, 36);
        getContentPane().add(jButton6, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String index = jTextField1.getText();
        String name = jTextField2.getText();

        String selectedItem = (String) jComboBox1.getSelectedItem();
        String excel = "A+";
        if ("A".equals(selectedItem)) {
            excel = "A";
        } else if ("A-".equals(selectedItem)) {
            excel = "A-";
        } else if ("B+".equals(selectedItem)) {
            excel = "B+";
        } else if ("B".equals(selectedItem)) {
            excel = "B";
        } else if ("B-".equals(selectedItem)) {
            excel = "B-";
        } else if ("C+".equals(selectedItem)) {
            excel = "C+";
        } else if ("C".equals(selectedItem)) {
            excel = "C";
        } else if ("C-".equals(selectedItem)) {
            excel = "C-";
        } else if ("D".equals(selectedItem)) {
            excel = "D";
        } else if ("F".equals(selectedItem)) {
            excel = "F";
        }

        String selectedItem1 = (String) jComboBox3.getSelectedItem();
        String word = "A+";
        if ("A".equals(selectedItem1)) {
            word = "A";
        } else if ("A-".equals(selectedItem1)) {
            word = "A-";
        } else if ("B+".equals(selectedItem1)) {
            word = "B+";
        } else if ("B".equals(selectedItem1)) {
            word = "B";
        } else if ("B-".equals(selectedItem1)) {
            word = "B-";
        } else if ("C+".equals(selectedItem1)) {
            word = "C+";
        } else if ("C".equals(selectedItem1)) {
            word = "C";
        } else if ("C-".equals(selectedItem1)) {
            word = "C-";
        } else if ("D".equals(selectedItem1)) {
            word = "D";
        } else if ("F".equals(selectedItem1)) {
            word = "F";
        }

        String selectedItem2 = (String) jComboBox4.getSelectedItem();
        String pp = "A+";
        if ("A".equals(selectedItem2)) {
            pp = "A";
        } else if ("A-".equals(selectedItem2)) {
            pp = "A-";
        } else if ("B+".equals(selectedItem2)) {
            pp = "B+";
        } else if ("B".equals(selectedItem2)) {
            pp = "B";
        } else if ("B-".equals(selectedItem2)) {
            pp = "B-";
        } else if ("C+".equals(selectedItem2)) {
            pp = "C+";
        } else if ("C".equals(selectedItem2)) {
            pp = "C";
        } else if ("C-".equals(selectedItem2)) {
            pp = "C-";
        } else if ("D".equals(selectedItem2)) {
            pp = "D";
        } else if ("F".equals(selectedItem2)) {
            pp = "F";
        }

        String selectedItem3 = (String) jComboBox2.getSelectedItem();
        String access = "A+";
        if ("A".equals(selectedItem3)) {
            access = "A";
        } else if ("A-".equals(selectedItem3)) {
            access = "A-";
        } else if ("B+".equals(selectedItem3)) {
            access = "B+";
        } else if ("B".equals(selectedItem3)) {
            access = "B";
        } else if ("B-".equals(selectedItem3)) {
            access = "B-";
        } else if ("C+".equals(selectedItem3)) {
            access = "C+";
        } else if ("C".equals(selectedItem3)) {
            access = "C";
        } else if ("C-".equals(selectedItem3)) {
            access = "C-";
        } else if ("D".equals(selectedItem3)) {
            access = "D";
        } else if ("F".equals(selectedItem3)) {
            access = "F";
        }

        String selectedItem4 = (String) jComboBox5.getSelectedItem();
        String statexc = "Repeat";
        if ("Pass".equals(selectedItem4)) {
            statexc = "Pass";
        }

        String selectedItem5 = (String) jComboBox6.getSelectedItem();
        String statwor = "Repeat";
        if ("Pass".equals(selectedItem5)) {
            statwor = "Pass";
        }

        String selectedItem6 = (String) jComboBox7.getSelectedItem();
        String statpp = "Repeat";
        if ("Pass".equals(selectedItem6)) {
            statpp = "Pass";
        }

        String selectedItem7 = (String) jComboBox8.getSelectedItem();
        String statacc = "Repeat";
        if ("Pass".equals(selectedItem7)) {
            statacc = "Pass";
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "INSERT INTO word (Index_Number, Student_Name, Grade, Status) VALUES ('" + index + "','" + name + "','" + word + "','" + statwor + "')";
            stmt.executeUpdate(sql);
            conn.close();


        } catch (Exception e) {
            e.printStackTrace();
        }


        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "INSERT INTO excel (Index_Number, Student_Name, Grade, Status) VALUES ('" + index + "','" + name + "','" + excel + "','" + statexc + "')";
            stmt.executeUpdate(sql);
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "INSERT INTO power_point (Index_Number, Student_Name, Grade, Status) VALUES ('" + index + "','" + name + "','" + pp + "','" + statpp + "')";
            stmt.executeUpdate(sql);
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "INSERT INTO access (Index_Number, Student_Name, Grade, Status) VALUES ('" + index + "','" + name + "','" + access + "','" + statacc + "')";
            stmt.executeUpdate(sql);
            conn.close();
            clearAll();
            JOptionPane.showMessageDialog(null, "Student results inserted successfully!");

        } catch (Exception e) {
            e.printStackTrace();
        }
        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String index = jTextField1.getText();
        
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false","root","");
                Statement stmt = conn.createStatement();
                String sql = "Select*from student_details where Index_Number = '"+index+"'";
                ResultSet rs = stmt.executeQuery(sql);
                boolean isNoResult = true;
                while(rs.next()){
                    isNoResult = false;
                    
                    jTextField2.setText(rs.getString("Student_Name"));

                }
                conn.close();
                if(isNoResult){
                    JOptionPane.showMessageDialog(null, "No Data from this Index Number!");
                }else{
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                }
        }catch(Exception e){
                e.printStackTrace();
        }
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false","root","");
                Statement stmt = conn.createStatement();
                String sql = "Select*from excel where Index_Number = '"+index+"'";
                ResultSet rs = stmt.executeQuery(sql);
                boolean isNoResult = true;
                while(rs.next()){
                    isNoResult = false;
                    
                    
                    String grade = rs.getString("Grade");
                    switch (grade) {
                        case "A+":
                            jComboBox1.setSelectedItem("A+");
                            break;
                        case "A":
                            jComboBox1.setSelectedItem("A");
                            break;
                        case "A-":
                            jComboBox1.setSelectedItem("A-");
                            break;
                        case "B+":
                            jComboBox1.setSelectedItem("B+");
                            break;
                        case "B":
                            jComboBox1.setSelectedItem("B");
                            break;
                        case "B-":
                            jComboBox1.setSelectedItem("B-");
                            break;
                        case "C+":
                            jComboBox1.setSelectedItem("C+");
                            break;
                        case "C":
                            jComboBox1.setSelectedItem("C");
                            break;
                        case "C-":
                            jComboBox1.setSelectedItem("C-");
                            break;
                        case "D":
                            jComboBox1.setSelectedItem("D");
                            break;
                        case "F":
                            jComboBox1.setSelectedItem("F");
                            break;
                    }
                    
                    String stat = rs.getString("Status");
                    switch (stat) {
                        case "Pass":
                            jComboBox5.setSelectedItem("Pass");
                            break;
                        case "Repeat":
                            jComboBox5.setSelectedItem("Repeat");
                            break;
                    }
                    

                }
                conn.close();
                if(isNoResult){
                    JOptionPane.showMessageDialog(null, "No Data from this Index Number!");
                }else{
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                }
        }catch(Exception e){
                e.printStackTrace();
        }
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false","root","");
                Statement stmt = conn.createStatement();
                String sql = "Select*from word where Index_Number = '"+index+"'";
                ResultSet rs = stmt.executeQuery(sql);
                boolean isNoResult = true;
                while(rs.next()){
                    isNoResult = false;
                    
                    String grade = rs.getString("Grade");
                    switch (grade) {
                        case "A+":
                            jComboBox3.setSelectedItem("A+");
                            break;
                        case "A":
                            jComboBox3.setSelectedItem("A");
                            break;
                        case "A-":
                            jComboBox3.setSelectedItem("A-");
                            break;
                        case "B+":
                            jComboBox3.setSelectedItem("B+");
                            break;
                        case "B":
                            jComboBox3.setSelectedItem("B");
                            break;
                        case "B-":
                            jComboBox3.setSelectedItem("B-");
                            break;
                        case "C+":
                            jComboBox3.setSelectedItem("C+");
                            break;
                        case "C":
                            jComboBox3.setSelectedItem("C");
                            break;
                        case "C-":
                            jComboBox3.setSelectedItem("C-");
                            break;
                        case "D":
                            jComboBox3.setSelectedItem("D");
                            break;
                        case "F":
                            jComboBox3.setSelectedItem("F");
                            break;
                    }
                    String stat = rs.getString("Status");
                    switch (stat) {
                        case "Pass":
                            jComboBox6.setSelectedItem("Pass");
                            break;
                        case "Repeat":
                            jComboBox6.setSelectedItem("Repeat");
                            break;
                    }
                    

                }
                conn.close();
                if(isNoResult){
                    JOptionPane.showMessageDialog(null, "No Data from this Index Number!");
                }else{
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                }
        }catch(Exception e){
                e.printStackTrace();
        }
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false","root","");
                Statement stmt = conn.createStatement();
                String sql = "Select*from power_point where Index_Number = '"+index+"'";
                ResultSet rs = stmt.executeQuery(sql);
                boolean isNoResult = true;
                while(rs.next()){
                    isNoResult = false;
                    
                    String grade = rs.getString("Grade");
                    switch (grade) {
                        case "A+":
                            jComboBox4.setSelectedItem("A+");
                            break;
                        case "A":
                            jComboBox4.setSelectedItem("A");
                            break;
                        case "A-":
                            jComboBox4.setSelectedItem("A-");
                            break;
                        case "B+":
                            jComboBox4.setSelectedItem("B+");
                            break;
                        case "B":
                            jComboBox4.setSelectedItem("B");
                            break;
                        case "B-":
                            jComboBox4.setSelectedItem("B-");
                            break;
                        case "C+":
                            jComboBox4.setSelectedItem("C+");
                            break;
                        case "C":
                            jComboBox4.setSelectedItem("C");
                            break;
                        case "C-":
                            jComboBox4.setSelectedItem("C-");
                            break;
                        case "D":
                            jComboBox4.setSelectedItem("D");
                            break;
                        case "F":
                            jComboBox4.setSelectedItem("F");
                            break;
                    }
                    String stat = rs.getString("Status");
                    switch (stat) {
                        case "Pass":
                            jComboBox7.setSelectedItem("Pass");
                            break;
                        case "Repeat":
                            jComboBox7.setSelectedItem("Repeat");
                            break;
                    }
                    

                }
                conn.close();
                if(isNoResult){
                    JOptionPane.showMessageDialog(null, "No Data from this Index Number!");
                }else{
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                }
        }catch(Exception e){
                e.printStackTrace();
        }
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false","root","");
                Statement stmt = conn.createStatement();
                String sql = "Select*from access where Index_Number = '"+index+"'";
                ResultSet rs = stmt.executeQuery(sql);
                boolean isNoResult = true;
                while(rs.next()){
                    isNoResult = false;
                    
                    String grade = rs.getString("Grade");
                    switch (grade) {
                        case "A+":
                            jComboBox2.setSelectedItem("A+");
                            break;
                        case "A":
                            jComboBox2.setSelectedItem("A");
                            break;
                        case "A-":
                            jComboBox2.setSelectedItem("A-");
                            break;
                        case "B+":
                            jComboBox2.setSelectedItem("B+");
                            break;
                        case "B":
                            jComboBox2.setSelectedItem("B");
                            break;
                        case "B-":
                            jComboBox2.setSelectedItem("B-");
                            break;
                        case "C+":
                            jComboBox2.setSelectedItem("C+");
                            break;
                        case "C":
                            jComboBox2.setSelectedItem("C");
                            break;
                        case "C-":
                            jComboBox2.setSelectedItem("C-");
                            break;
                        case "D":
                            jComboBox2.setSelectedItem("D");
                            break;
                        case "F":
                            jComboBox2.setSelectedItem("F");
                            break;
                    }
                    String stat = rs.getString("Status");
                    switch (stat) {
                        case "Pass":
                            jComboBox8.setSelectedItem("Pass");
                            break;
                        case "Repeat":
                            jComboBox8.setSelectedItem("Repeat");
                            break;
                    }
                    

                }
                conn.close();
                if(isNoResult){
                    JOptionPane.showMessageDialog(null, "No Data from this Index Number!");
                }else{
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                }
        }catch(Exception e){
                e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String index = jTextField1.getText();
        String name = jTextField2.getText();

        String selectedItem = (String) jComboBox1.getSelectedItem();
        String excel = "A+";
        if ("A".equals(selectedItem)) {
            excel = "A";
        } else if ("A-".equals(selectedItem)) {
            excel = "A-";
        } else if ("B+".equals(selectedItem)) {
            excel = "B+";
        } else if ("B".equals(selectedItem)) {
            excel = "B";
        } else if ("B-".equals(selectedItem)) {
            excel = "B-";
        } else if ("C+".equals(selectedItem)) {
            excel = "C+";
        } else if ("C".equals(selectedItem)) {
            excel = "C";
        } else if ("C-".equals(selectedItem)) {
            excel = "C-";
        } else if ("D".equals(selectedItem)) {
            excel = "D";
        } else if ("F".equals(selectedItem)) {
            excel = "F";
        }

        String selectedItem1 = (String) jComboBox3.getSelectedItem();
        String word = "A+";
        if ("A".equals(selectedItem1)) {
            word = "A";
        } else if ("A-".equals(selectedItem1)) {
            word = "A-";
        } else if ("B+".equals(selectedItem1)) {
            word = "B+";
        } else if ("B".equals(selectedItem1)) {
            word = "B";
        } else if ("B-".equals(selectedItem1)) {
            word = "B-";
        } else if ("C+".equals(selectedItem1)) {
            word = "C+";
        } else if ("C".equals(selectedItem1)) {
            word = "C";
        } else if ("C-".equals(selectedItem1)) {
            word = "C-";
        } else if ("D".equals(selectedItem1)) {
            word = "D";
        } else if ("F".equals(selectedItem1)) {
            word = "F";
        }

        String selectedItem2 = (String) jComboBox4.getSelectedItem();
        String pp = "A+";
        if ("A".equals(selectedItem2)) {
            pp = "A";
        } else if ("A-".equals(selectedItem2)) {
            pp = "A-";
        } else if ("B+".equals(selectedItem2)) {
            pp = "B+";
        } else if ("B".equals(selectedItem2)) {
            pp = "B";
        } else if ("B-".equals(selectedItem2)) {
            pp = "B-";
        } else if ("C+".equals(selectedItem2)) {
            pp = "C+";
        } else if ("C".equals(selectedItem2)) {
            pp = "C";
        } else if ("C-".equals(selectedItem2)) {
            pp = "C-";
        } else if ("D".equals(selectedItem2)) {
            pp = "D";
        } else if ("F".equals(selectedItem2)) {
            pp = "F";
        }

        String selectedItem3 = (String) jComboBox2.getSelectedItem();
        String access = "A+";
        if ("A".equals(selectedItem3)) {
            access = "A";
        } else if ("A-".equals(selectedItem3)) {
            access = "A-";
        } else if ("B+".equals(selectedItem3)) {
            access = "B+";
        } else if ("B".equals(selectedItem3)) {
            access = "B";
        } else if ("B-".equals(selectedItem3)) {
            access = "B-";
        } else if ("C+".equals(selectedItem3)) {
            access = "C+";
        } else if ("C".equals(selectedItem3)) {
            access = "C";
        } else if ("C-".equals(selectedItem3)) {
            access = "C-";
        } else if ("D".equals(selectedItem3)) {
            access = "D";
        } else if ("F".equals(selectedItem3)) {
            access = "F";
        }

        String selectedItem4 = (String) jComboBox5.getSelectedItem();
        String statexc = "Repeat";
        if ("Pass".equals(selectedItem4)) {
            statexc = "Pass";
        }

        String selectedItem5 = (String) jComboBox6.getSelectedItem();
        String statwor = "Repeat";
        if ("Pass".equals(selectedItem5)) {
            statwor = "Pass";
        }

        String selectedItem6 = (String) jComboBox7.getSelectedItem();
        String statpp = "Repeat";
        if ("Pass".equals(selectedItem6)) {
            statpp = "Pass";
        }

        String selectedItem7 = (String) jComboBox8.getSelectedItem();
        String statacc = "Repeat";
        if ("Pass".equals(selectedItem7)) {
            statacc = "Pass";
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Update word SET Index_Number = '" + index + "', Student_Name = '" + name + "', Grade = '" + word + "', Status = '" + statwor + "' where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();


        } catch (Exception e) {
            e.printStackTrace();
        }


        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Update excel SET Index_Number = '" + index + "', Student_Name = '" + name + "', Grade = '" + excel + "', Status = '" + statexc + "' where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Update power_point SET Index_Number = '" + index + "', Student_Name = '" + name + "', Grade = '" + pp + "', Status = '" + statpp + "' where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Update access SET Index_Number = '" + index + "', Student_Name = '" + name + "', Grade = '" + access + "', Status = '" + statacc + "' where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();
            clearAll();
            JOptionPane.showMessageDialog(null, "Student results upadated successfully!");

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String index = jTextField1.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Delete from word where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();


        } catch (Exception e) {
            e.printStackTrace();
        }


        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Delete from excel where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Delete from power_point where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "Delete from access where Index_Number = '" + index + "'";
            stmt.executeUpdate(sql);
            conn.close();
            clearAll();
            JOptionPane.showMessageDialog(null, "Student results deleted successfully!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Administrator nextForm = new Administrator();
        nextForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1MouseExited

    private void jTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1MouseReleased

    private void jComboBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseMoved
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox1MouseMoved

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String grade = (String) jComboBox1.getSelectedItem();
        switch (grade) {
                case "A+":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "A":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "A-":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "B+":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "B":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "B-":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "C+":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "C":
                    jComboBox5.setSelectedItem("Pass");
                    break;
                case "C-":
                    jComboBox5.setSelectedItem("Repeat");
                    break;
                case "D":
                    jComboBox5.setSelectedItem("Repeat");
                    break;
                case "F":
                    jComboBox5.setSelectedItem("Repeat");
                    break;
            }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        String grade = (String) jComboBox3.getSelectedItem();
        switch (grade) {
                case "A+":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "A":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "A-":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "B+":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "B":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "B-":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "C+":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "C":
                    jComboBox6.setSelectedItem("Pass");
                    break;
                case "C-":
                    jComboBox6.setSelectedItem("Repeat");
                    break;
                case "D":
                    jComboBox6.setSelectedItem("Repeat");
                    break;
                case "F":
                    jComboBox6.setSelectedItem("Repeat");
                    break;
            }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        String grade = (String) jComboBox4.getSelectedItem();
        switch (grade) {
                case "A+":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "A":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "A-":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "B+":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "B":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "B-":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "C+":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "C":
                    jComboBox7.setSelectedItem("Pass");
                    break;
                case "C-":
                    jComboBox7.setSelectedItem("Repeat");
                    break;
                case "D":
                    jComboBox7.setSelectedItem("Repeat");
                    break;
                case "F":
                    jComboBox7.setSelectedItem("Repeat");
                    break;
            }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        
        String grade = (String) jComboBox2.getSelectedItem();
        switch (grade) {
                case "A+":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "A":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "A-":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "B+":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "B":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "B-":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "C+":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "C":
                    jComboBox8.setSelectedItem("Pass");
                    break;
                case "C-":
                    jComboBox8.setSelectedItem("Repeat");
                    break;
                case "D":
                    jComboBox8.setSelectedItem("Repeat");
                    break;
                case "F":
                    jComboBox8.setSelectedItem("Repeat");
                    break;
            }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseMoved

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        String index = jTextField1.getText();
        
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wsdom_moodle?useSSL=false","root","");
                Statement stmt = conn.createStatement();
                String sql = "Select*from student_details where Index_Number = '"+index+"'";
                ResultSet rs = stmt.executeQuery(sql);
                boolean isNoResult = true;
                while(rs.next()){
                    isNoResult = false;
                    
                    jTextField2.setText(rs.getString("Student_Name"));

                }
                conn.close();
                if(isNoResult){
                    JOptionPane.showMessageDialog(null, "No Data from this Index Number!");
                }
        }catch(Exception e){
                e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
